In [14]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score

In [15]:
df = pd.read_csv("data/customer_churn_cleaned.csv")

In [16]:
df.drop("customerID", axis=1, inplace=True)

In [17]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [18]:
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns

categorical_features = X.select_dtypes(include="object").columns

In [19]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:
lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(max_iter=1000))
    ]
)

lr_pipeline.fit(X_train, y_train)

lr_pred = lr_pipeline.predict(X_test)

print("Logistic Regression Accuracy :", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy : 0.8038379530916845

In [9]:
dt_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", DecisionTreeClassifier(random_state=42))
    ]
)

dt_pipeline.fit(X_train, y_train)

dt_pred = dt_pipeline.predict(X_test)

print("Decision Tree Accuracy :", accuracy_score(y_test, dt_pred))

Decision Tree Accuracy : 0.7306325515280739

In [10]:
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(random_state=42))
    ]
)

rf_pipeline.fit(X_train, y_train)

rf_pred = rf_pipeline.predict(X_test)

print("Random Forest Accuracy :", accuracy_score(y_test, rf_pred))

Random Forest Accuracy : 0.7874911158493249

In [11]:
gb_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", GradientBoostingClassifier(random_state=42))
    ]
)

gb_pipeline.fit(X_train, y_train)

gb_pred = gb_pipeline.predict(X_test)

print("Gradient Boosting Accuracy :", accuracy_score(y_test, gb_pred))

Gradient Boosting Accuracy : 0.7960199004975125

In [12]:
results = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],

    "Accuracy":[

        accuracy_score(y_test, lr_pred),

        accuracy_score(y_test, dt_pred),

        accuracy_score(y_test, rf_pred),

        accuracy_score(y_test, gb_pred)

    ]

})

results

                 Model  Accuracy
0  Logistic Regression  0.803838
1        Decision Tree  0.730633
2        Random Forest  0.787491
3    Gradient Boosting  0.796020

In [13]:
results.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy
0  Logistic Regression  0.803838
3    Gradient Boosting  0.796020
2        Random Forest  0.787491
1        Decision Tree  0.730633

In [22]:
print(X.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']